### ISSUE TITLE
Creating Windows forms interface

### ISSUE THREAD

**Issue by JamesMatchett** [HeckingCode/CSharp-Basic-Encryption-Pack#2]
Righty-o need to have a little discussion about what we want the UI to look like/what functionality it has to have so just comment your suggestions below, I'm going to mockup a few sketches and lists of potential functions, lemme know what you think :)

**Comment by JamesMatchett** [comment]
@JordanGibson is handling the first part of the UI just to get the ball rolling.

**Comment by JordanGibson** [comment]
First draft of UI complete and merged with master.

**Comment by JamesMatchett** [comment]
First draft complete with PR #5
